---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: "{{ .Values.dataScienceProjectNamespace }}"
  labels:
    app: models-pvc
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi