---
# Cluster Role named route-reader that can reader openshift routes
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  name: route-reader
  namespace: {{ .Values.dataScienceProjectNamespace }}
rules:
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  name: setup-job
  namespace: {{ .Values.dataScienceProjectNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  name: setup-job-edit
  namespace: {{ .Values.dataScienceProjectNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: setup-job
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  name: setup-job-route-reader-binding
  namespace: {{ .Values.dataScienceProjectNamespace }}
subjects:
- kind: ServiceAccount
  name: setup-job
  namespace: {{ .Values.dataScienceProjectNamespace }}
roleRef:
  kind: Role
  name: route-reader
  apiGroup: rbac.authorization.k8s.io