namespace: vllm-mistral-7b

createNamespace: true

vcs:
  uri: https://github.com/alpha-hack-program/doc-bot.git
  ref: main
  name: alpha-hack-program/doc-bot
  path: examples/ui/gradio-rag-milvus-vllm-openai

model:
  name: mistral-7b