namespace: vllm-mistral-7b

language: en

createNamespace: true

pythonImage:
  version: "3.9"
  name: "python"
  tag: "3.9-ubi8"

vcs:
  uri: https://github.com/alpha-hack-program/doc-bot.git
  ref: main
  name: alpha-hack-program/doc-bot
  path: examples/ui/gradio-rag-milvus-vllm-openai
  # sourceSecret: git-pat-bc-secret

model:
  name: mistral-7b

milvus:
  name: milvus
  namespace: milvus
  username: root
  password: Milvus
  port: '19530'
  host: vectordb-milvus

mountCaCerts: "false"