#!/bin/sh

. .env

podman tag $IMAGE_NAME:$IMAGE_VERSION $REGISTRY/$REGISTRY_USER_ID/$IMAGE_NAME:$IMAGE_VERSION
podman tag $IMAGE_NAME:$IMAGE_VERSION $REGISTRY/$REGISTRY_USER_ID/$IMAGE_NAME:latest
podman push $REGISTRY/$REGISTRY_USER_ID/$IMAGE_NAME:$IMAGE_VERSION
podman push $REGISTRY/$REGISTRY_USER_ID/$IMAGE_NAME:latest