ARG FROM_IMAGE
FROM ${FROM_IMAGE} AS BASE

# Install git, curl, and necessary dependencies
RUN dnf install -y git jq tar gzip unzip && \
    dnf clean all

# Install python3
RUN dnf install -y python3 pip && \
    dnf clean all

# Install huggingface hub cli without cache directory
RUN pip install --no-cache-dir -U "huggingface_hub[cli]" && \
    rm -rf /root/.cache

# Install the latest version of the OC CLI
ENV OC_VERSION=4.14.27
RUN curl -o /tmp/oc.tar.gz -L https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/${OC_VERSION}/openshift-client-linux-${OC_VERSION}.tar.gz && cd /usr/bin && tar -xvzf /tmp/oc.tar.gz && chmod a+x /usr/bin/oc && chmod a+x /usr/bin/kubectl && rm -f /tmp/oc.tar.gz

# Install the latest version of aws cli
RUN curl -o /tmp/awscliv2.zip "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" && \
    unzip /tmp/awscliv2.zip -d /tmp && \
    /tmp/aws/install && \
    rm -rf /tmp/awscliv2.zip  /tmp/aws

# Create the directory and set permissions
RUN mkdir -p /scratch && \
    chown -R 1001:0 /scratch && \
    chmod -R g+rwX /scratch

ENV AWS_CONFIG_FILE=/scratch/aws-config

# Set the working directory
WORKDIR /workspace