apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.chatApplication.name }}
  namespace: {{ .Values.argocdNamespace }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: "{{ .Values.dataScienceProjectNamespace }}"
  source:
    path: "{{ .Values.chatApplication.path }}"
    repoURL: "{{ .Values.chatApplication.repoURL }}"
    targetRevision: "{{ .Values.chatApplication.targetRevision }}"
    helm:
      parameters:
        - name: argocdNamespace
          value: {{ .Values.argocdNamespace }}
        - name: createNamespace
          value: "false"
        - name: namespace
          value: "{{ .Values.dataScienceProjectNamespace }}"
        - name: model.name
          value: "{{ .Values.model.name }}"
        - name: language
          value: "{{ .Values.chatApplication.language }}"
        - name: vcs.uri
          value: "{{ .Values.chatApplication.vcs.uri }}"
        - name: vcs.ref
          value: "{{ .Values.chatApplication.vcs.ref }}"
        - name: vcs.name
          value: "{{ .Values.chatApplication.vcs.name }}"
        - name: vcs.path
          value: "{{ .Values.chatApplication.vcs.path }}"
        - name: milvus.name
          value: "{{ .Values.milvus.name }}"
        - name: milvus.namespace
          value: "{{ .Values.milvus.namespace }}"
        - name: milvus.username
          value: "{{ .Values.milvus.username }}"
        - name: milvus.password
          value: "{{ .Values.milvus.password }}"
        - name: milvus.port
          value: "{{ .Values.milvus.port }}"
        - name: milvus.host
          value: "{{ .Values.milvus.host }}"
        - name: mountCaCerts
          value: "{{ .Values.mountCaCerts }}"
  syncPolicy:
    automated:
      # prune: true
      selfHeal: true