apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: "false"
    app.openshift.io/vcs-ref: {{ .Values.vcs.ref }}
    app.openshift.io/vcs-uri: {{ .Values.vcs.uri }}
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"doc-bot:latest","namespace":"{{ .Values.dataScienceProjectNamespace }}"},"fieldPath":"spec.template.spec.containers[?(@.name==\"doc-bot\")].image","pause":"false"}]'
  labels:
    app: doc-bot
    app.kubernetes.io/component: doc-bot
    app.kubernetes.io/instance: doc-bot
    app.kubernetes.io/name: doc-bot
    app.kubernetes.io/part-of: doc-bot
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
  name: doc-bot
  namespace: {{ .Values.dataScienceProjectNamespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: doc-bot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: doc-bot
        deployment: doc-bot
    spec:
      serviceAccountName: doc-bot-ui
      containers:
        - envFrom:
            - secretRef:
                name: doc-bot-env
          image: image-registry.openshift-image-registry.svc:5000/{{ .Values.dataScienceProjectNamespace }}/doc-bot:latest
          imagePullPolicy: Always
          name: doc-bot
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: {{ .Values.vcs.ref }}
    app.openshift.io/vcs-uri: {{ .Values.vcs.uri }}
  labels:
    app: doc-bot
    app.kubernetes.io/component: doc-bot
    app.kubernetes.io/instance: doc-bot
    app.kubernetes.io/name: doc-bot
    app.kubernetes.io/part-of: doc-bot
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
  name: doc-bot
  namespace: {{ .Values.dataScienceProjectNamespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 7860-tcp
      port: 7860
      protocol: TCP
      targetPort: 7860
  selector:
    app: doc-bot
    deployment: doc-bot
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
stringData:
  APP_TITLE: "Chat with your Knowledge Base!"
  SHOW_TITLE_IMAGE: "True"
  INFERENCE_SERVER_URL: "https://mistral-7b-vllm-mistral-7b.apps.cluster-pwkqj.sandbox2852.opentlc.com/v1"
  MODEL_NAME: "/mnt/models/"
  MAX_TOKENS: "1024"
  TOP_P: "0.95"
  TEMPERATURE: "0.01"
  PRESENCE_PENALTY: "1.03"
  MILVUS_HOST: "vectordb-milvus.milvus"
  MILVUS_PORT: "19530"
  MILVUS_USERNAME: "root"
  MILVUS_PASSWORD: "Milvus"
  MILVUS_COLLECTIONS_FILE: "./collections.json"
  DEFAULT_COLLECTION: "none"
  PROMPT_FILE: "default_prompt.txt"
  MAX_RETRIEVED_DOCS: "4"
  SCORE_THRESHOLD: "0.99"
kind: Secret
metadata:
  labels:
    app: doc-bot
  name: doc-bot-env
  namespace: {{ .Values.dataScienceProjectNamespace }}
type: Opaque
---
apiVersion: v1
data:
  WebHookSecretKey: ZmIzNGU3NTUyNDE3OTM1Zg==
kind: Secret
metadata:
  labels:
    app: doc-bot
    app.kubernetes.io/component: doc-bot
    app.kubernetes.io/instance: doc-bot
    app.kubernetes.io/name: doc-bot
    app.kubernetes.io/part-of: doc-bot
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
  name: doc-bot-generic-webhook-secret
  namespace: {{ .Values.dataScienceProjectNamespace }}
type: Opaque
---
apiVersion: v1
data:
  WebHookSecretKey: N2E5MTA3ZTY0MzQ5MzM0NQ==
kind: Secret
metadata:
  labels:
    app: doc-bot
    app.kubernetes.io/component: doc-bot
    app.kubernetes.io/instance: doc-bot
    app.kubernetes.io/name: doc-bot
    app.kubernetes.io/part-of: doc-bot
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
  name: doc-bot-github-webhook-secret
  namespace: {{ .Values.dataScienceProjectNamespace }}
type: Opaque
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: {{ .Values.vcs.ref }}
    app.openshift.io/vcs-uri: {{ .Values.vcs.uri }}
  labels:
    app: doc-bot
    app.kubernetes.io/component: doc-bot
    app.kubernetes.io/instance: doc-bot
    app.kubernetes.io/name: doc-bot
    app.kubernetes.io/part-of: doc-bot
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
  name: doc-bot
  namespace: {{ .Values.dataScienceProjectNamespace }}
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: {{ .Values.vcs.ref }}
    app.openshift.io/vcs-uri: {{ .Values.vcs.uri }}
  labels:
    app: doc-bot
    app.kubernetes.io/component: doc-bot
    app.kubernetes.io/instance: doc-bot
    app.kubernetes.io/name: doc-bot
    app.kubernetes.io/part-of: doc-bot
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
  name: doc-bot
  namespace: {{ .Values.dataScienceProjectNamespace }}
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: doc-bot:latest
  runPolicy: Serial
  source:
    contextDir: {{ .Values.paths.ui }}
    git:
      uri: {{ .Values.vcs.uri }}
      ref: {{ .Values.vcs.ref }}
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.9-ubi8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - generic:
        secretReference:
          name: doc-bot-generic-webhook-secret
      type: Generic
    - github:
        secretReference:
          name: doc-bot-github-webhook-secret
      type: GitHub
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: doc-bot
    app.kubernetes.io/component: doc-bot
    app.kubernetes.io/instance: doc-bot
    app.kubernetes.io/name: doc-bot
    app.kubernetes.io/part-of: doc-bot
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
  name: doc-bot
  namespace: {{ .Values.dataScienceProjectNamespace }}
spec:
  port:
    targetPort: 7860-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: doc-bot
    weight: 100
  wildcardPolicy: None
