kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-{{ .Values.documentsConnection.name }}
  namespace: {{ .Values.dataScienceProjectNamespace }}
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Set sync-wave to -1 to avoid conflicts with other resources
    opendatahub.io/connection-type: {{ .Values.documentsConnection.type }}
    openshift.io/display-name: {{ .Values.documentsConnection.displayName }}
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.documentsConnection.awsAccessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.documentsConnection.awsSecretAccessKey }}
  AWS_DEFAULT_REGION: {{ .Values.documentsConnection.awsDefaultRegion }}
  AWS_S3_BUCKET: {{ .Values.documentsConnection.awsS3Bucket }}
  AWS_S3_ENDPOINT: {{ printf "%s://%s" .Values.documentsConnection.scheme .Values.documentsConnection.awsS3Endpoint }}
  
type: Opaque
