apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.embeddingsApplication.name }}-gpu
  namespace: {{ .Values.argocdNamespace }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: "{{ .Values.dataScienceProjectNamespace }}"
  source:
    path: "gitops/models" # This should be {{ .Values.embeddingsApplication.path }}
    repoURL: "{{ .Values.embeddingsApplication.repoURL }}"
    targetRevision: "{{ .Values.embeddingsApplication.targetRevision }}"
    helm:
      helm:
      values: |
        dataScienceProjectDisplayName: {{ .Values.dataScienceProjectNamespace }}
        dataScienceProjectNamespace: {{ .Values.dataScienceProjectNamespace }}
        
        createNamespace: false

        instanceName: {{ .Values.embeddingsApplication.model.name }}

        model:
          root: {{ .Values.embeddingsApplication.model.root }}
          id: {{ .Values.embeddingsApplication.model.id }}
          name: {{ .Values.embeddingsApplication.model.name }}
          displayName: {{ .Values.embeddingsApplication.model.displayName }}
          maxReplicas: {{ .Values.embeddingsApplication.model.maxReplicas }}
          format: {{ .Values.embeddingsApplication.model.format }}
          maxModelLen: {{ .Values.embeddingsApplication.model.maxModelLen }}
          apiProtocol: {{ .Values.embeddingsApplication.model.apiProtocol }}
          embeddingsModel: {{ .Values.embeddingsApplication.model.embeddingsModel }}
          enableAuth: {{ .Values.embeddingsApplication.model.enableAuth }}
          rawDeployment: {{ .Values.embeddingsApplication.model.rawDeployment }}
          runtime:
            templateName: {{ .Values.embeddingsApplication.model.runtime.templateName }}
            templateDisplayName: {{ .Values.embeddingsApplication.model.runtime.templateDisplayName }}
            image: {{ .Values.embeddingsApplication.model.runtime.image }}
            resources:
              limits:
                cpu: {{ .Values.embeddingsApplication.model.runtime.resources.limits.cpu }}
                memory: {{ .Values.embeddingsApplication.model.runtime.resources.limits.memory }}
              requests:
                cpu: {{ .Values.embeddingsApplication.model.runtime.resources.requests.cpu }}
                memory: {{ .Values.embeddingsApplication.model.runtime.resources.requests.memory }}
        {{- if .Values.embeddingsApplication.model.accelerator }}
          accelerator:
            max: {{ .Values.embeddingsApplication.model.accelerator.max }}
            min: {{ .Values.embeddingsApplication.model.accelerator.min }}
            productName: {{ .Values.embeddingsApplication.model.accelerator.productName }}
        {{- end }}
          connection:
            name: {{ .Values.embeddingsApplication.model.connection.name }}
            createSecret: {{ .Values.embeddingsApplication.model.connection.createSecret }}
            displayName: {{ .Values.embeddingsApplication.model.connection.displayName }}
            type: {{ .Values.embeddingsApplication.model.connection.type }}
            scheme: {{ .Values.embeddingsApplication.model.connection.scheme }}
            awsAccessKeyId: {{ .Values.embeddingsApplication.model.connection.awsAccessKeyId }}
            awsSecretAccessKey: {{ .Values.embeddingsApplication.model.connection.awsSecretAccessKey }}
            awsDefaultRegion: {{ .Values.embeddingsApplication.model.connection.awsDefaultRegion }}
            awsS3Bucket: {{ .Values.embeddingsApplication.model.connection.awsS3Bucket }}
            awsS3Endpoint: {{ .Values.embeddingsApplication.model.connection.awsS3Endpoint }}
          volumes:
            shm:
              sizeLimit: {{ .Values.embeddingsApplication.model.volumes.shm.sizeLimit }}
  syncPolicy:
    automated:
      # prune: true
      selfHeal: true