kind: Secret
apiVersion: v1
metadata:
  name: openai-connection-embeddings
  namespace: {{ .Values.dataScienceProjectNamespace }}
stringData:
  OPENAI_API_KEY: ''
  OPENAI_API_MODEL: '{{ .Values.embeddingsApplication.model.name }}'
  OPENAI_API_BASE: 'http://{{ .Values.embeddingsApplication.model.name }}-predictor.{{ .Values.dataScienceProjectNamespace }}.svc.cluster.local:8080'
  
type: Opaque
