kind: Secret
apiVersion: v1
metadata:
  name: openai-connection-{{ .Values.embeddingsApplication.model.name }}
  namespace: {{ .Values.dataScienceProjectNamespace }}
stringData:
  OPENAI_API_KEY: ''
  OPENAI_API_MODEL: '{{ .Values.embeddingsApplication.model.name }}'
  OPENAI_API_BASE: 'http://{{ .Values.embeddingsApplication.model.name }}.{{ .Values.dataScienceProjectNamespace }}.svc.cluster.local'
  
type: Opaque
