---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-setup
  namespace: {{ .Values.dataScienceProjectNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-setup-edit
  namespace: {{ .Values.dataScienceProjectNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: demo-setup
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-setup-route-reader-binding
subjects:
- kind: ServiceAccount
  name: demo-setup
  namespace: {{ .Values.dataScienceProjectNamespace }}
subjects:
- kind: ServiceAccount
  name: demo-setup
  namespace: {{ .Values.minio.namespace }}
roleRef:
  kind: ClusterRole
  name: route-reader
  apiGroup: rbac.authorization.k8s.io