apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.modelApplication.name }}
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: "{{ .Values.dataScienceProjectNamespace }}"
  source:
    path: "{{ .Values.modelApplication.path }}"
    repoURL: "{{ .Values.modelApplication.repoURL }}"
    targetRevision: "{{ .Values.modelApplication.targetRevision }}"
    helm:
      parameters:
        - name: createNamespace
          value: "false"
        - name: instanceName
          value: "{{ .Values.model.name }}"
        - name: dataScienceProjectNamespace
          value: "{{ .Values.dataScienceProjectNamespace }}"
        - name: dataScienceProjectDisplayName
          value: "{{ .Values.dataScienceProjectDisplayName }}"
        - name: model.root
          value: "{{ .Values.model.root }}"
        - name: model.id
          value: "{{ .Values.model.id }}"
        - name: model.name
          value: "{{ .Values.model.name }}"
        - name: model.displayName
          value: "{{ .Values.model.displayName }}"
        - name: model.accelerator.productName
          value: "{{ .Values.model.accelerator.productName }}"
        - name: model.accelerator.min
          value: '{{ .Values.model.accelerator.min }}'
        - name: model.accelerator.max
          value: '{{ .Values.model.accelerator.max }}'
        - name: modelConnection.name
          value: "{{ .Values.modelConnection.name }}"
        - name: modelConnection.displayName
          value: "{{ .Values.modelConnection.displayName }}"
        - name: modelConnection.type
          value: "{{ .Values.modelConnection.type }}"
        - name: modelConnection.scheme
          value: "{{ .Values.modelConnection.scheme }}"
        - name: modelConnection.awsAccessKeyId
          value: "{{ .Values.modelConnection.awsAccessKeyId }}"
        - name: modelConnection.awsSecretAccessKey
          value: "{{ .Values.modelConnection.awsSecretAccessKey }}"
        - name: modelConnection.awsDefaultRegion
          value: "{{ .Values.modelConnection.awsDefaultRegion }}"
        - name: modelConnection.awsS3Bucket
          value: "{{ .Values.modelConnection.awsS3Bucket }}"
        - name: modelConnection.awsS3Endpoint
          value: "{{ .Values.modelConnection.awsS3Endpoint }}"
        - name: milvus.name
          value: "{{ .Values.milvus.name }}"
        - name: milvus.namespace
          value: "{{ .Values.milvus.namespace }}"
        - name: milvus.username
          value: "{{ .Values.milvus.username }}"
        - name: milvus.password
          value: "{{ .Values.milvus.password }}"
        - name: milvus.port
          value: "{{ .Values.milvus.port }}"
        - name: milvus.host
          value: "{{ .Values.milvus.host }}"
  syncPolicy:
    automated:
      # prune: true
      selfHeal: true