kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-{{ .Values.modelConnection.name }}
  namespace: {{ .Values.dataScienceProjectNamespace }}
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Set sync-wave to -1 to avoid conflicts with other resources
    opendatahub.io/connection-type: {{ .Values.modelConnection.type }}
    openshift.io/display-name: {{ .Values.modelConnection.displayName }}
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.modelConnection.awsAccessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.modelConnection.awsSecretAccessKey }}
  AWS_DEFAULT_REGION: {{ .Values.modelConnection.awsDefaultRegion }}
  AWS_S3_BUCKET: {{ .Values.modelConnection.awsS3Bucket }}
  AWS_S3_ENDPOINT: {{ printf "%s://%s" .Values.modelConnection.scheme .Values.modelConnection.awsS3Endpoint }}
  
type: Opaque
