apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.modelApplication.name }}
  namespace: {{ .Values.argocdNamespace }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: "{{ .Values.dataScienceProjectNamespace }}"
  source:
    path: "{{ .Values.modelApplication.path }}"
    repoURL: "{{ .Values.modelApplication.repoURL }}"
    targetRevision: "{{ .Values.modelApplication.targetRevision }}"
    helm:
      parameters:
        - name: argocdNamespace
          value: {{ .Values.argocdNamespace }}
        - name: createNamespace
          value: "false"
        - name: instanceName
          value: "{{ .Values.model.name }}"
        - name: dataScienceProjectNamespace
          value: "{{ .Values.dataScienceProjectNamespace }}"
        - name: dataScienceProjectDisplayName
          value: "{{ .Values.dataScienceProjectDisplayName }}"
        - name: model.root
          value: "{{ .Values.model.root }}"
        - name: model.id
          value: "{{ .Values.model.id }}"
        - name: model.name
          value: "{{ .Values.model.name }}"
        - name: model.displayName
          value: "{{ .Values.model.displayName }}"
        - name: model.accelerator.productName
          value: "{{ .Values.model.accelerator.productName }}"
        - name: model.accelerator.min
          value: '{{ .Values.model.accelerator.min }}'
        - name: model.accelerator.max
          value: '{{ .Values.model.accelerator.max }}'
        - name: model.connection.createSecret
          value: "{{ .Values.modelConnection.createSecret }}"
        - name: model.connection.name
          value: "{{ .Values.modelConnection.name }}"
        - name: model.connection.displayName
          value: "{{ .Values.modelConnection.displayName }}"
        - name: model.connection.type
          value: "{{ .Values.modelConnection.type }}"
        - name: model.connection.scheme
          value: "{{ .Values.modelConnection.scheme }}"
        - name: model.connection.awsAccessKeyId
          value: "{{ .Values.modelConnection.awsAccessKeyId }}"
        - name: model.connection.awsSecretAccessKey
          value: "{{ .Values.modelConnection.awsSecretAccessKey }}"
        - name: model.connection.awsDefaultRegion
          value: "{{ .Values.modelConnection.awsDefaultRegion }}"
        - name: model.connection.awsS3Bucket
          value: "{{ .Values.modelConnection.awsS3Bucket }}"
        - name: model.connection.awsS3Endpoint
          value: "{{ .Values.modelConnection.awsS3Endpoint }}"
  syncPolicy:
    automated:
      # prune: true
      selfHeal: true