kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-{{ .Values.pipelinesConnection.name }}
  namespace: {{ .Values.dataScienceProjectNamespace }}
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: {{ .Values.pipelinesConnection.type }}
    openshift.io/display-name: {{ .Values.pipelinesConnection.displayName }}
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.pipelinesConnection.awsAccessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.pipelinesConnection.awsSecretAccessKey }}
  AWS_DEFAULT_REGION: {{ .Values.pipelinesConnection.awsDefaultRegion }}
  AWS_S3_BUCKET: {{ .Values.pipelinesConnection.awsS3Bucket }}
  AWS_S3_ENDPOINT: {{ printf "%s://%s" .Values.pipelinesConnection.scheme .Values.pipelinesConnection.awsS3Endpoint }}
  
type: Opaque
