argocdNamespace: openshift-gitops

vcs:
  uri: https://github.com/alpha-hack-program/doc-bot.git
  ref: main
  name: alpha-hack-program/doc-bot

paths:
  ui: examples/ui/gradio-rag-milvus-vllm-openai

modelApplication:
  name: doc-bot-model
  repoURL: https://github.com/alpha-hack-program/model-serving-utils.git
  path: gitops/model
  targetRevision: main
  model:
    root: mistralai
    id: Mistral-7B-Instruct-v0.2
    name: mistral-7b
    displayName: Mistral 7b
    maxReplicas: 1
    enableAuth: false
    rawDeployment: false
    runtime:
      templateName: vllm-serving-template
      templateDisplayName: vLLM Serving Template
      image: quay.io/modh/vllm:rhoai-2.20-cuda
      resources:
        limits:
          cpu: '8'
          memory: 24Gi
        requests:
          cpu: '6'
          memory: 24Gi
    accelerator:
      max: '1'
      min: '1'
      productName: NVIDIA-A10G
    connection:
      name: llm
      createSecret: true
      displayName: LLM
      type: s3
      scheme: http
      awsAccessKeyId: minio
      awsSecretAccessKey: minio123
      awsDefaultRegion: none
      awsS3Bucket: models
      awsS3Endpoint: minio.ic-shared-minio.svc:9000
    volumes:
      shm:
        sizeLimit: 2Gi

embeddingsApplication:
  name: doc-bot-embeddings
  repoURL: https://github.com/alpha-hack-program/model-serving-utils.git
  path: gitops/model
  targetRevision: main
  model:
    root: intfloat
    id: multilingual-e5-large
    name: multilingual-e5-large-gpu
    displayName: multilingual-e5-large GPU
    maxReplicas: 1
    format: vLLM
    maxModelLen: '512'
    apiProtocol: REST
    enableAuth: false
    rawDeployment: true
    runtime:
      templateName: vllm-serving-template
      templateDisplayName: vLLM Serving Template
      image: quay.io/modh/vllm:rhoai-2.20-cuda
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 4Gi
    accelerator:
      max: '1'
      min: '1'
      productName: NVIDIA-A10G
    connection:
      name: embeddings-svc
      createSecret: true
      displayName: embeddings-svc
      type: s3
      scheme: http
      awsAccessKeyId: minio
      awsSecretAccessKey: minio123
      awsDefaultRegion: none
      awsS3Bucket: models
      awsS3Endpoint: minio.ic-shared-minio.svc:9000
    volumes:
      shm:
        sizeLimit: 2Gi

pipelinesApplication:
  name: doc-bot-pipelines
  repoURL: https://github.com/alpha-hack-program/doc-bot.git
  path: gitops/pipelines
  targetRevision: main

chatApplication:
  name: doc-bot-chat
  repoURL: https://github.com/alpha-hack-program/doc-bot.git
  path: gitops/kb-chat
  targetRevision: main
  language: en
  vcs:
    uri: https://github.com/alpha-hack-program/doc-bot.git
    ref: main
    name: alpha-hack-program/doc-bot
    path: examples/ui/gradio-rag-milvus-vllm-openai

kotaemonApplication:
  name: doc-bot-kotaemon
  repoURL: https://github.com/alpha-hack-program/doc-bot-kotaemon.git
  path: gitops/kotaemon
  targetRevision: main
  language: en
  vcs:
    uri: https://github.com/alpha-hack-program/doc-bot-kotaemon.git
    ref: main
    name: alpha-hack-program/doc-bot-kotaemon
    path: src

dataScienceProjectDisplayName: vllm-mistral-7b
dataScienceProjectNamespace: vllm-mistral-7b

instanceName: vllm-mistral-7b

model:
  root: mistralai
  id: Mistral-7B-Instruct-v0.2
  name: mistral-7b
  displayName: Mistral 7b
  maxReplicas: 1
  enableAuth: false
  rawDeployment: false
  runtime:
    resources:
      limits:
        cpu: '8'
        memory: 24Gi
      requests:
        cpu: '6'
        memory: 24Gi
  accelerator:
    max: '1'
    min: '1'
    productName: NVIDIA-A10G
  connection:
    name: llm
    createSecret: true
    displayName: embeddings
    type: s3
    scheme: http
    awsAccessKeyId: minio
    awsSecretAccessKey: minio123
    awsDefaultRegion: none
    awsS3Bucket: models
    awsS3Endpoint: minio.ic-shared-minio.svc:9000
  volumes:
    shm:
      sizeLimit: 2Gi

embeddings:
  root: nomic-ai
  id: nomic-embed-text-v1
  name: nomic-embed-text-v1
  displayName: Nomic Embed Text v1
  maxReplicas: 1
  format: pytorch
  apiProtocol: REST
  enableAuth: false
  rawDeployment: false
  runtime:
    templateName: nomic-serving-template
    templateDisplayName: Nomic Serving Template
    resources:
      limits:
        cpu: '2'
        memory: 8Gi
      requests:
        cpu: '1'
        memory: 4Gi
  # accelerator:
  #   max: '1'
  #   min: '1'
  #   productName: NVIDIA-A10G
  connection:
    name: embeddings
    createSecret: true
    displayName: embeddings
    type: s3
    scheme: http
    awsAccessKeyId: minio
    awsSecretAccessKey: minio123
    awsDefaultRegion: none
    awsS3Bucket: models
    awsS3Endpoint: minio.ic-shared-minio.svc:9000
  volumes:
    shm:
      sizeLimit: 2Gi

workbench:
  name: rag-workbench
  displayName: RAG Workbench
  namespace: rag-workbench
  image: pytorch:2024.1
  resources:
    limits:
      cpu: '2'
      memory: 8Gi
      # nvidiaGpu: '1'
    requests:
      cpu: '1'
      memory: 6Gi
      # nvidiaGpu: '1'
    
modelConnection:
  createSecret: true
  name: llm
  displayName: llm
  type: s3
  scheme: http
  awsAccessKeyId: minio
  awsSecretAccessKey: minio123
  awsDefaultRegion: none
  awsS3Bucket: models
  awsS3Endpoint: minio.ic-shared-minio.svc:9000

documentsConnection:
  name: documents
  displayName: documents
  type: s3
  scheme: http
  awsAccessKeyId: minio
  awsSecretAccessKey: minio123
  awsDefaultRegion: none
  awsS3Bucket: documents
  awsS3Endpoint: minio.ic-shared-minio.svc:9000

pipelinesConnection:
  name: pipelines
  displayName: pipelines
  type: s3
  scheme: http
  awsAccessKeyId: minio
  awsSecretAccessKey: minio123
  awsDefaultRegion: none
  awsS3Bucket: pipelines
  awsS3Endpoint: minio.ic-shared-minio.svc:9000

minio:
  name: minio
  namespace: ic-shared-minio

documentsMilvusConnection:
  name: documents
  collectionName: documents

milvus:
  name: milvus
  namespace: milvus
  username: root
  password: Milvus
  port: '19530'
  host: vectordb-milvus

setup:
  image: quay.io/atarazana/hf-cli:latest

mountCaCerts: "false"