apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: "{{ .Values.instanceName }}"
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: "{{ .Values.kfpUpsertTektonPipelineName }}-github"
  name: el-{{ .Values.kfpUpsertTektonPipelineName }}-github
  namespace: {{ .Values.dataScienceProjectNamespace }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.kfpUpsertTektonPipelineName }}-github
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: "{{ .Values.instanceName }}"
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: "{{ .Values.kfpUpsertTektonPipelineName }}-gitea"
  name: el-{{ .Values.kfpUpsertTektonPipelineName }}-gitea
  namespace: {{ .Values.dataScienceProjectNamespace }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.kfpUpsertTektonPipelineName }}-gitea
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: "{{ .Values.instanceName }}"
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: "{{ .Values.kfpUpsertTektonPipelineName }}-gitlab"
  name: el-{{ .Values.kfpUpsertTektonPipelineName }}-gitlab
  namespace: {{ .Values.dataScienceProjectNamespace }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.kfpUpsertTektonPipelineName }}-gitlab
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None