apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/displayName: Upload a Pipeline to a KFP cluster
    tekton.dev/pipelines.minVersion: '0.19'
    tekton.dev/tags: 'kfp'
  name: kfp-upload
  namespace: {{ .Values.dataScienceProjectNamespace }}
  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/provider-type: redhat
spec:
  description: >-
    These Task will compile and upload a Pipeline to a KFP cluster
  params:
    - description: The image used where python is installed
      name: TASK_IMAGE
      type: string
      # default: quay.io/modh/runtime-images:runtime-cuda-tensorflow-ubi9-python-3.9-2023b-20240301
      default: image-registry.openshift-image-registry.svc:5000/openshift/{{ .Values.pythonImage.name }}:{{ .Values.pythonImage.tag }}
    - description: The pipeline python script to compile
      name: PIPELINE_NAME
      type: string
      default: deploy
    - description: The requiretments file to install
      name: REQUIREMENTS_FILE
      type: string
      default: requirements.txt
    - description: The path to the pipeline python script
      name: PIPELINES_PATH
      type: string
      default: pipeline
    - description: Added files
      name: ADDED_FILES
      type: string
    - description: Removed files
      name: REMOVED_FILES
      type: string
    - description: Modified files
      name: MODIFIED_FILES
      type: string
    - description: Force upsert
      name: FORCE_UPSERT
      type: string
      default: 'false'
  results:
    - description: Pipelines files to upsert 
      name: PIPELINE_FILES_TO_UPSERT
    - description: Pipelines files to remove 
      name: PIPELINE_FILES_TO_REMOVE
    - description: The Pipeline Id of the kfp pipeline uploaded
      name: PIPELINE_ID
  steps:
    - image: $(params.TASK_IMAGE)
      name: compile
      resources: {}
      workingDir: $(workspaces.source.path)
      env:
        - name: PIPELINE_NAME
          value: $(params.PIPELINE_NAME)
        - name: PIPELINES_PATH
          value: $(params.PIPELINES_PATH)
        - name: ADD_FILES
          value: $(params.ADDED_FILES)
        - name: REMOVED_FILES
          value: $(params.REMOVED_FILES)
        - name: MODIFIED_FILES
          value: $(params.MODIFIED_FILES)
        - name: REQUIREMENTS_FILE
          value: $(params.REQUIREMENTS_FILE)
        - name: FORCE_UPSERT
          value: $(params.FORCE_UPSERT)
      {{- if .Values.mountCaCerts }}
      volumeMounts:
        - name: kfp-upsert-cacerts
          mountPath: /opt/app-root/lib/python{{ .Values.python }}/site-packages/certifi/cacert.pem
          subPath: cacert.pem
          readOnly: true
      {{- end }}
      script: >
        #!/bin/sh

        echo "Added files: ${ADDED_FILES}"

        echo "Removed files: ${REMOVED_FILES}"
        
        echo "Modified files: ${MODIFIED_FILES}"

        echo "Current directory $(pwd)"

        echo "List files"
        
        ls -lstrh

        cd ${PIPELINES_PATH}

        pip install -r $(params.REQUIREMENTS_FILE)

        echo "FORCE_UPSERT: ${FORCE_UPSERT}"

        python <<EOF

        # Example variables

        modified_files = "${MODIFIED_FILES}"

        added_files = "${ADDED_FILES}"

        removed_files = "${REMOVED_FILES}"

        pipelines_dir = "${PIPELINES_PATH}"


        pipeline_files_to_upsert_file_path="$(results.PIPELINE_FILES_TO_UPSERT.path)"

        pipeline_files_to_remove_file_path="$(results.PIPELINE_FILES_TO_REMOVE.path)"


        # Function to filter and clean file paths

        def filter_pl_f(files_str, pipelines_dir):
            # Split the string into a list of paths
            files_list = files_str.split()
            # Filter paths that match the pipelines directory and end with .py
            filtered_files = [
                file for file in files_list 
                if file.startswith(pipelines_dir) and file.endswith('.py')
            ]
            # Remove the pipelines directory prefix
            filtered_files = [
                file[len(pipelines_dir)+1:] for file in filtered_files
            ]
            return filtered_files

        # Function to determine if a file is a pipeline file.

        def is_pipeline_file(file_path):
            with open(file_path, 'r') as file:
                for line in file:
                    # Check if the line contains the pipeline decorator
                    if 'dsl.pipeline' in line:
                        return True
            return False
                    
        # Filter each set of files

        filtered_mod = filter_pl_f(modified_files, pipelines_dir)

        filtered_add = filter_pl_f(added_files, pipelines_dir)

        filtered_rem = filter_pl_f(removed_files, pipelines_dir)


        # Join added and modified files

        filtered_add_mod = filtered_add + filtered_mod

        # If FORCE_UPSERT is true, list all python files

        force_upsert = "${FORCE_UPSERT}"

        if force_upsert == 'true':
            import os

            # List all files in the current directory
            files_in_directory = os.listdir('.')

            # Filter out only .py files and join the file names with a blank space
            filtered_add_mod = [file for file in files_in_directory if file.endswith('.py')]

        print(f'{force_upsert} => {filtered_add_mod}')

        # Output the intermediate results

        print("Filtered Added + Modified Files:", filtered_add_mod)

        print("Filtered Removed Files:", filtered_rem)


        # Check if the added or modified files are pipeline files

        # and add themto a list

        pipeline_files_to_upsert = []

        for file in filtered_add_mod:
            if is_pipeline_file(file):
                pipeline_files_to_upsert.append(file)

        # Print the pipeline files to upsert

        print("Pipeline Files to Upsert:", pipeline_files_to_upsert)


        # Check if the removed files are pipeline files and add them to a list

        pipeline_files_to_remove = []

        for file in filtered_rem:
            if is_pipeline_file(file):
                pipeline_files_to_remove.append(file)

        # Print the pipeline files to remove

        print("Pipeline Files to Remove:", pipeline_files_to_remove)

        # Write the file paths to the respective files

        print("Writing Upserts to:", pipeline_files_to_upsert_file_path)

        with open(pipeline_files_to_upsert_file_path, 'w') as f:
            f.write(' '.join(pipeline_files_to_upsert))
        with open(pipeline_files_to_remove_file_path, 'w') as f:
            f.write(' '.join(pipeline_files_to_remove))

        # Print the contents of the files
        with open(pipeline_files_to_upsert_file_path, 'r') as f:
            print("Upserts:", f.read())

        EOF

        echo "About to iterate Pipeline files to upsert"

        # Iterate Pipeline files to upsert

        PIPELINES_UPSERT="$(cat /tekton/results/PIPELINE_FILES_TO_UPSERT)"

        echo "PIPELINES_UPSERT=${PIPELINES_UPSERT}"

        for file in ${PIPELINES_UPSERT}; do
          python ${file}
        done
  workspaces:
    - mountPath: /workspace/source
      name: source
  # Mount if mountCaCerts is true
  {{- if .Values.mountCaCerts }}
  volumes:
    - name: kfp-upsert-cacerts
      configMap:
        name: kfp-upsert-cacerts
  {{- end }}
