---
{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.dataScienceProjectNamespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    openshift.io/description: "{{ .Values.dataScienceProjectDisplayName }}"
    openshift.io/display-name: '{{ .Values.dataScienceProjectDisplayName }}'
  labels:
    argocd.argoproj.io/managed-by: {{ .Values.argocdNamespace }} #argocd instance ns
    kubernetes.io/metadata.name: "{{ .Values.dataScienceProjectNamespace }}"
    modelmesh-enabled: 'false'
    opendatahub.io/dashboard: 'true'
{{- end }}