---
# Role named setup-jobs-role that can reader openshift routes
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: pipelines-setup-jobs-role
rules:
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: pipelines-setup-jobs
  namespace: {{ .Values.dataScienceProjectNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: pipelines-setup-jobs-edit
  namespace: {{ .Values.dataScienceProjectNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipelines-setup-jobs
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: pipelines-setup-jobs-role-binding
  namespace: {{ .Values.dataScienceProjectNamespace }}
subjects:
- kind: ServiceAccount
  name: pipelines-setup-jobs
  namespace: {{ .Values.dataScienceProjectNamespace }}
roleRef:
  kind: Role
  name: pipelines-setup-jobs-role
  apiGroup: rbac.authorization.k8s.io